import Link from 'next/link'
import { ArrowRight, BarChart3, Boxes, Building2, Check, CheckCircle2, ChevronDown, CircleGauge, Clock3, FileText, Globe2, GraduationCap, HeartPulse, Layers3, LockKeyhole, PackageSearch, Play, ReceiptText, ShieldCheck, ShoppingBag, Sparkles, Stethoscope, TrendingUp, Truck, Users, UsersRound, UtensilsCrossed, Wrench } from 'lucide-react'
import { ContactForm } from '@/components/ContactForm'
import { CostBuilder } from '@/components/CostBuilder'
import { modules } from '@/components/product-data'

const industries = [
  { name: 'Retail ERP', icon: ShoppingBag, size: '5–100 employees', price: 122, modules: ['Inventory', 'CRM', 'Payroll'], result: 'Control stock, customers and people from one system.' },
  { name: 'Hospitality ERP', icon: UtensilsCrossed, size: '1–20 locations', price: 138, modules: ['Restaurant', 'Inventory', 'HR'], result: 'Connect front-of-house, kitchen and workforce operations.' },
  { name: 'Healthcare ERP', icon: Stethoscope, size: '10–250 employees', price: 152, modules: ['Healthcare', 'HR', 'Payroll'], result: 'Coordinate teams and secure operational workflows.' },
  { name: 'Construction ERP', icon: Wrench, size: '10–200 employees', price: 127, modules: ['Projects', 'Fleet', 'Payroll'], result: 'Track jobs, vehicles, labour and project performance.' },
  { name: 'Logistics ERP', icon: Truck, size: '5–150 vehicles', price: 138, modules: ['Fleet', 'Inventory', 'Payroll'], result: 'Manage moving assets, stock and driver operations.' },
  { name: 'Education ERP', icon: GraduationCap, size: '50–1,000 learners', price: 92, modules: ['CRM', 'HR', 'Help Desk'], result: 'Simplify admissions, staff and service requests.' },
]

const demos = [
  { id: 'crm-demo', name: 'CRM Demo', label: 'SALES', icon: UsersRound, outcome: 'Turn every enquiry into a visible, accountable next step.', stats: ['£91k pipeline', '34 opportunities'], type: 'pipeline' },
  { id: 'hr-demo', name: 'HR Demo', label: 'PEOPLE', icon: Building2, outcome: 'Give managers a live view of headcount, leave and performance.', stats: ['248 employees', '96% records complete'], type: 'people' },
  { id: 'payroll-demo', name: 'Payroll Demo', label: 'FINANCE', icon: ReceiptText, outcome: 'Move from payroll inputs to approved runs with fewer handoffs.', stats: ['248 payslips', 'Ready for approval'], type: 'payroll' },
  { id: 'inventory-demo', name: 'Inventory Demo', label: 'OPERATIONS', icon: PackageSearch, outcome: 'See stock risks before they interrupt fulfilment or cash flow.', stats: ['1,842 SKUs', '12 low-stock alerts'], type: 'stock' },
]

const faqs = [
  ['Can we start with only one module?', 'Yes. The £19 core platform gives you a secure workspace, analytics and marketplace access. Activate one business module and add more whenever the value is clear.'],
  ['How does pay-as-you-go pricing work?', 'Your monthly subscription is the core platform, active modules and any users above the included allowance. Modules can be activated or removed without replacing the platform.'],
  ['How does multi-tenancy work?', 'Each organisation operates in a securely isolated tenant with its own users, roles, data, modules and subscription.'],
  ['Can we move away from spreadsheets gradually?', 'Yes. Most customers begin with the workflow causing the most friction, prove value, then connect adjacent teams on the same data foundation.'],
]

function DemoVisual({ type }: { type: string }) {
  if (type === 'pipeline') return <div className="demo-screen pipeline-screen"><div className="demo-screen-top"><span>Sales pipeline</span><b>+ Opportunity</b></div><div className="mini-kanban"><div><small>QUALIFIED · 8</small><i><b>Northstar Group</b><span>£24,500</span></i><i><b>Oak & Reed</b><span>£8,900</span></i></div><div><small>PROPOSAL · 5</small><i className="highlight"><b>Brightline Ltd</b><span>£31,800</span></i><i><b>Acumen UK</b><span>£12,400</span></i></div><div><small>WON · 11</small><i><b>Medoria</b><span>£18,200</span></i><i><b>North & Co.</b><span>£9,750</span></i></div></div></div>
  if (type === 'people') return <div className="demo-screen people-screen"><div className="demo-screen-top"><span>Employee overview</span><b>August</b></div><div className="people-stats"><i><small>HEADCOUNT</small><b>248</b><em>+8 this month</em></i><i><small>ON LEAVE</small><b>14</b><em>5 departments</em></i><i><small>REVIEWS DUE</small><b>22</b><em>Next 30 days</em></i></div><div className="people-list"><span><i>SK</i><b>Sarah Khan</b><em>Operations</em></span><span><i>JM</i><b>James Miller</b><em>Sales</em></span><span><i>LP</i><b>Lucy Price</b><em>People</em></span></div></div>
  if (type === 'payroll') return <div className="demo-screen payroll-screen"><div className="demo-screen-top"><span>August payroll</span><b>Review run</b></div><div className="payroll-total"><small>NET PAY</small><strong>£486,240</strong><span>248 employees</span></div><div className="payroll-steps"><i className="done"><Check /> Inputs</i><i className="done"><Check /> Calculated</i><i className="current"><Clock3 /> Approval</i><i>Payment</i></div><div className="approval-row"><span><ShieldCheck />Checks passed</span><b>12 / 12</b></div></div>
  return <div className="demo-screen stock-screen"><div className="demo-screen-top"><span>Inventory health</span><b>3 locations</b></div><div className="stock-chart"><span style={{ height: '78%' }} /><span style={{ height: '54%' }} /><span className="alert" style={{ height: '25%' }} /><span style={{ height: '69%' }} /><span style={{ height: '88%' }} /><span style={{ height: '46%' }} /></div><div className="stock-alert"><PackageSearch /><div><b>12 items need attention</b><small>4 purchase orders suggested</small></div><ArrowRight /></div></div>
}

export default function Home() {
  return <>
    <section className="hero marketplace-hero"><div className="shell hero-grid"><div className="hero-copy"><div className="eyebrow"><Sparkles /> Pay-as-you-go ERP for UK SMEs</div><h1>Build the ERP your business needs. <em>Nothing more.</em></h1><p>Start with one module. Add CRM, payroll, HR, inventory and specialist tools as you grow—all inside one secure cloud platform.</p><div className="hero-actions"><Link className="button" href="#cost-builder">Build My ERP <ArrowRight /></Link><Link className="text-link" href="#demos"><span><Play /></span> See Live Demo</Link></div><div className="hero-proof"><span><Check /> From £19/month</span><span><Check /> 14-day free trial</span><span><Check /> No long-term contract</span></div></div><div className="hero-product expanded-product" aria-label="Digital Services ERP connected dashboard preview"><div className="product-window"><div className="window-top"><b><span>DS</span> Digital Services</b><div className="window-search">Search customers, people, stock…</div><i>AK</i></div><div className="window-body"><aside><b>Overview</b><span>CRM</span><span>People</span><span>Payroll</span><span>Inventory</span><span>Projects</span><span>Finance</span></aside><div className="window-content"><div className="preview-heading"><div><small>MONDAY, 24 AUGUST</small><h3>One business. One live view.</h3></div><button>+ New</button></div><div className="metrics"><article><small>CRM PIPELINE</small><strong>£91,240</strong><span className="up">34 opportunities</span></article><article><small>EMPLOYEES</small><strong>248</strong><span>14 on leave</span></article><article><small>OPEN INVOICES</small><strong>£18,750</strong><span className="up">↗ 8 paid today</span></article></div><div className="preview-panels"><article><div className="panel-title"><b>Revenue analytics</b><span>Last 6 months</span></div><div className="chart"><i style={{height:'34%'}}/><i style={{height:'48%'}}/><i style={{height:'42%'}}/><i style={{height:'63%'}}/><i style={{height:'71%'}}/><i className="active" style={{height:'91%'}}/></div></article><article><div className="panel-title"><b>Stock & tasks</b><span>Live</span></div><ul><li><i className="red"/>12 low-stock items <small>Review</small></li><li><i/>Payroll approval <small>11:00</small></li><li><i/>Client review <small>14:30</small></li></ul></article></div></div></div></div><div className="floating-card float-one"><CheckCircle2 /><span><small>Module connected</small><b>Payroll is now live</b></span></div><div className="floating-card float-two"><Layers3 /><span><small>Active modules</small><b>6 of 9</b></span><em>Pay as you go</em></div></div></div></section>

    <section className="trust-strip"><div className="shell"><p>Built for growing UK businesses that have outgrown disconnected software</p><div><span>Northstar</span><span>ASTER & CO.</span><span>VANTAGE</span><span>MEDORIA</span><span>BRIGHTLINE</span></div></div></section>

    <section className="section value-section"><div className="shell"><div className="section-heading compact"><div><span className="kicker">Why Digital Services ERP</span><h2>ERP value without ERP lock-in.</h2></div><p>Buy the capability you need now, keep one shared source of truth, and expand without a costly system replacement.</p></div><div className="value-grid">{[['Start with one module','Solve the clearest operational problem first.'],['Add modules anytime','Connect the next team without reimplementation.'],['No long-term contracts','Keep flexibility as priorities change.'],['UK-focused workflows','Built around how UK SMEs operate.'],['Cloud-based access','Work securely from any authorised device.'],['Secure data storage','Tenant isolation and role-based controls.'],['Scalable infrastructure','Grow users, locations and workflows confidently.']].map(([title,text],index)=><article key={title}><span>0{index+1}</span><CheckCircle2/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="section muted" id="modules"><div className="shell"><div className="section-heading"><div><span className="kicker">ERP module marketplace</span><h2>Choose capability.<br/>Not shelfware.</h2></div><div><p>Every module is a complete product with shared users, permissions, data and reporting. Start free, prove the value, then keep only what works.</p><Link className="text-arrow" href="/marketplace">Browse the marketplace <ArrowRight /></Link></div></div><div className="conversion-module-grid">{modules.map(({id,name,price,icon:Icon,category,features})=><article className="conversion-module-card" key={id}><div className="module-card-head"><div className="module-icon"><Icon/></div><span>{category}</span></div><h3>{name}</h3><div className="module-price">From <b>£{price}</b><span>/month</span></div><ul>{features.map(feature=><li key={feature}><Check/>{feature}</li>)}</ul><div className="module-card-actions"><Link className="button" href={`/register?module=${id}`}>Start Free Trial</Link><Link className="button button-outline" href={`#${id.includes('hr')?'hr-demo':id.includes('payroll')?'payroll-demo':id.includes('inventory')?'inventory-demo':'crm-demo'}`}>View Demo</Link></div></article>)}</div></div></section>

    <section className="section builder-section" id="cost-builder"><div className="shell"><div className="section-heading compact"><div><span className="kicker">ERP cost builder</span><h2>Calculate your ERP in seconds.</h2></div><p>Select modules, adjust your team size and see a clear monthly estimate before speaking to anyone.</p></div><CostBuilder /></div></section>

    <section className="section industry-packages" id="industries"><div className="shell"><div className="section-heading"><div><span className="kicker">Ready-made starting points</span><h2>ERP packages shaped around your industry.</h2></div><p>Begin with a recommended combination, then adjust every module to match your operation and budget.</p></div><div className="package-grid">{industries.map(({name,icon:Icon,size,price,modules:recommended,result})=><article key={name}><div className="package-icon"><Icon/></div><h3>{name}</h3><p>{result}</p><div className="package-meta"><span>Typical size <b>{size}</b></span><span>Starting from <b>£{price}/mo</b></span></div><small>RECOMMENDED MODULES</small><div className="package-modules">{recommended.map(module=><span key={module}>{module}</span>)}</div><Link href="#cost-builder">Configure package <ArrowRight/></Link></article>)}</div></div></section>

    <section className="section demo-section" id="demos"><div className="shell"><div className="section-heading"><div><span className="kicker light">Explore interactive demos</span><h2>See the work.<br/>Not just the promise.</h2></div><p>Explore how each module turns everyday operational data into a clear next action.</p></div><div className="demo-grid">{demos.map(({id,name,label,icon:Icon,outcome,stats,type})=><article id={id} key={id}><DemoVisual type={type}/><div className="demo-copy"><span><Icon/>{label}</span><h3>{name}</h3><p>{outcome}</p><div>{stats.map(stat=><b key={stat}>{stat}</b>)}</div><Link className="button button-white" href="/register">Start Free Trial <ArrowRight/></Link></div></article>)}</div></div></section>

    <section className="section architecture-section"><div className="shell architecture-grid"><div><span className="kicker">Platform architecture</span><h2>One core.<br/>Every module connected.</h2><p>The core platform provides your secure tenant, users, permissions, analytics, automation and subscription controls. You only pay for the business modules you activate.</p><ul><li><Check/>One login and permission model</li><li><Check/>Shared records across teams</li><li><Check/>One consolidated subscription</li><li><Check/>Modules activate without migration</li></ul><Link className="button" href="#cost-builder">Calculate My Cost <ArrowRight/></Link></div><div className="architecture-visual"><div className="core-node"><span>DS</span><b>CORE PLATFORM</b><small>£19 / month</small></div><div className="module-orbit">{['CRM','HR','Payroll','Inventory','Projects','Finance','Help Desk'].map((module,index)=><span style={{'--i':index} as React.CSSProperties} key={module}>{module}</span>)}</div><div className="architecture-caption"><LockKeyhole/><span><b>Secure shared data layer</b><small>Pay only for activated modules</small></span></div></div></div></section>

    <section className="section dashboard-story"><div className="shell"><div className="section-heading compact"><div><span className="kicker">Connected dashboard</span><h2>Every module adds context.</h2></div><p>Sales, people, operations and finance stop reporting in isolation. The dashboard turns them into one operating picture.</p></div><div className="dashboard-showcase"><aside><span className="active"><CircleGauge/>Overview</span><span><UsersRound/>CRM</span><span><Users/>People</span><span><ReceiptText/>Payroll</span><span><Boxes/>Inventory</span><span><FileText/>Invoices</span><span><BarChart3/>Analytics</span></aside><div className="dashboard-showcase-main"><header><div><small>EXECUTIVE OVERVIEW</small><h3>Good morning, Alex.</h3></div><button>Export report</button></header><div className="dashboard-showcase-metrics"><article><span>CRM pipeline</span><b>£91,240</b><small className="green">↗ 12.4%</small></article><article><span>Employees</span><b>248</b><small>14 on leave</small></article><article><span>Inventory health</span><b>94%</b><small className="red">12 alerts</small></article><article><span>Open invoices</span><b>£18,750</b><small>8 due this week</small></article></div><div className="dashboard-showcase-lower"><article><div><b>Revenue analytics</b><span>£284,620 this month</span></div><svg viewBox="0 0 600 180" role="img" aria-label="Revenue trend increasing over six months"><path d="M0 150 C65 130 80 145 130 118 S220 105 270 92 S365 110 415 60 S520 72 600 22"/></svg></article><article><div><b>Tasks across modules</b><span>Today</span></div><ul><li><i className="crm-dot"/><span><b>Follow up Northstar</b><small>CRM · 09:30</small></span></li><li><i className="payroll-dot"/><span><b>Approve August payroll</b><small>Payroll · 11:00</small></span></li><li><i className="stock-dot"/><span><b>Review stock alerts</b><small>Inventory · 14:00</small></span></li></ul></article></div></div></div></div></section>

    <section className="section proof-section"><div className="shell"><div className="proof-metrics"><article><strong>45%</strong><span>less time spent on repetitive administration</span></article><article><strong>£12k</strong><span>estimated annual software and process savings</span></article><article><strong>2.4×</strong><span>faster monthly management reporting</span></article><article><strong>99.9%</strong><span>platform availability target</span></article></div><div className="case-study-grid"><article className="featured-case"><span>OPERATIONS CASE STUDY</span><blockquote>“We stopped asking which spreadsheet had the latest number. Every team now works from the same live picture.”</blockquote><div><b>Sarah Khan</b><small>Chief Operating Officer, Northstar Group</small></div><Link href="#contact">Read the case study <ArrowRight/></Link></article><article><span>RETAIL</span><h3>One stock view across three locations.</h3><p>Inventory and purchasing moved from weekly reconciliation to live exception management.</p><b>38% fewer stock-outs</b></article><article><span>PROFESSIONAL SERVICES</span><h3>From lead to delivery without rekeying.</h3><p>CRM opportunities now create connected projects, budgets and client activity.</p><b>8 hours saved each week</b></article></div></div></section>

    <section className="section growth-section"><div className="shell"><div className="growth-heading"><span className="kicker light">Future-ready ERP</span><h2>Grow without changing systems.</h2><p>Your ERP should expand with the business—not become another platform you eventually outgrow.</p></div><div className="growth-path"><article><span>01 · START</span><h3>CRM only</h3><strong>£29<small>/month + platform</small></strong><p>Centralise leads, customers and quotations.</p><div><b>CRM</b></div></article><i><ArrowRight/></i><article><span>02 · GROWTH</span><h3>Connected teams</h3><strong>£93<small>/month + platform</small></strong><p>Connect sales, people and payroll.</p><div><b>CRM</b><b>HR</b><b>Payroll</b></div></article><i><ArrowRight/></i><article><span>03 · SCALE</span><h3>Full ERP suite</h3><strong>Built to fit</strong><p>Run every department on one shared platform.</p><div><b>CRM</b><b>People</b><b>Operations</b><b>Finance</b></div></article></div><div className="growth-cta"><div><ShieldCheck/><span><b>Your data foundation stays the same.</b><small>Add capability without starting again.</small></span></div><Link className="button button-white" href="/register">Start Free Trial <ArrowRight/></Link></div></div></section>

    <section className="section faq-section"><div className="shell faq-grid"><div><span className="kicker">Questions, answered</span><h2>Buy less software. Get more clarity.</h2><p>Need a tailored answer? Our ERP specialists can map the marketplace to your current operation.</p><Link className="text-arrow" href="#contact">Talk to a specialist <ArrowRight /></Link></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown /></summary><p>{a}</p></details>)}</div></div></section>

    <section className="section contact-section" id="contact"><div className="shell contact-grid"><div><span className="kicker light">Build your ERP</span><h2>Start with the workflow that matters most.</h2><p>Tell us where your team loses time today. We’ll help you choose the smallest, clearest starting point.</p><div className="contact-points"><span><Globe2 /> UK-focused implementation support</span><span><TrendingUp /> Tailored cost and ROI review</span><span><ShieldCheck /> Security and architecture consultation</span></div></div><ContactForm /></div></section>
  </>
}
