'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, Building2, Check, UsersRound } from 'lucide-react'
import { modules } from './product-data'

export function OnboardingForm(){
  const router=useRouter(); const [step,setStep]=useState(1); const [selected,setSelected]=useState(['crm','projects']); const [error,setError]=useState('')
  async function finish(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const form=new FormData(event.currentTarget);const response=await fetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyName:form.get('companyName'),industry:form.get('industry'),teamSize:form.get('teamSize'),modules:selected})});if(response.ok)router.push('/dashboard');else setError('Sign in before creating your workspace.')}
  return <form className="onboarding-card" onSubmit={finish}><div className="onboarding-progress"><span className={step>=1?'done':''}>1</span><i/><span className={step>=2?'done':''}>2</span><i/><span className={step>=3?'done':''}>3</span></div>{step===1&&<div className="onboarding-step"><div className="step-icon"><Building2/></div><span className="kicker">Step 1 of 3</span><h1>Tell us about your organisation.</h1><p>This creates your isolated workspace and helps tailor the setup.</p><label>Company name<input name="companyName" required placeholder="Acme Operations Ltd"/></label><label>Industry<select name="industry" required defaultValue=""><option value="" disabled>Select your industry</option><option value="professional_services">Professional services</option><option value="retail">Retail & distribution</option><option value="healthcare">Healthcare</option><option value="hospitality">Hospitality</option><option value="construction">Construction</option><option value="logistics">Transport & logistics</option></select></label><label>Team size<select name="teamSize" required defaultValue="11-50"><option>1-10</option><option>11-50</option><option>51-200</option><option>201-500</option><option>500+</option></select></label><button type="button" className="button" onClick={()=>setStep(2)}>Continue <ArrowRight/></button></div>}{step===2&&<div className="onboarding-step wide-step"><div className="step-icon"><UsersRound/></div><span className="kicker">Step 2 of 3</span><h1>Choose your starting modules.</h1><p>You can change these at any time. Your 14-day trial includes every selection.</p><div className="onboarding-modules">{modules.slice(0,6).map(({id,name,icon:Icon})=><button type="button" key={id} className={selected.includes(id)?'selected':''} onClick={()=>setSelected(selected.includes(id)?selected.filter(item=>item!==id):[...selected,id])}><Icon/><span>{name}</span>{selected.includes(id)&&<Check/>}</button>)}</div><div className="step-actions"><button type="button" className="button button-outline" onClick={()=>setStep(1)}>Back</button><button type="button" className="button" onClick={()=>setStep(3)}>Continue <ArrowRight/></button></div></div>}{step===3&&<div className="onboarding-step"><div className="step-icon"><Check/></div><span className="kicker">Step 3 of 3</span><h1>Your workspace is ready to build.</h1><p>We’ll create your secure tenant with {selected.length} starting modules and a 14-day platform trial.</p><div className="setup-summary"><span>Workspace isolation <b>Enabled</b></span><span>Selected modules <b>{selected.length}</b></span><span>Trial period <b>14 days</b></span><span>Payment required <b>No</b></span></div>{error&&<p className="auth-error">{error}</p>}<div className="step-actions"><button type="button" className="button button-outline" onClick={()=>setStep(2)}>Back</button><button className="button">Create workspace <ArrowRight/></button></div></div>}</form>
}
