'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Check, Plus, Search } from 'lucide-react'
import { modules } from '@/components/product-data'

export default function MarketplacePage() {
  const [query,setQuery]=useState(''); const [selected,setSelected]=useState<string[]>([])
  const filtered=modules.filter(module=>`${module.name} ${module.description}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="page-wrap"><section className="market-hero"><div className="shell"><span className="kicker">Digital Services ERP App Store</span><h1>Start with one.<br />Add the rest later.</h1><p>Activate complete business modules on demand. Every app shares the same company workspace, users, permissions, and data foundation.</p><label className="market-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search modules or features"/></label></div></section><section className="shell marketplace-grid">{filtered.map(({id,name,description,price,usagePricing,icon:Icon,category,features})=>{const active=selected.includes(id);return <article id={id} className="market-module" key={id}><div className="market-module-head"><div className="module-icon"><Icon/></div><span>{category}</span></div><h2><Link href={`/modules/${id}`}>{name}</Link></h2><p>{description}</p><ul>{features.map(feature=><li key={feature}><Check/>{feature}</li>)}</ul><div className="market-module-price"><span>From <b>£{price}</b> / month<small>{usagePricing}</small></span><button className={active?'module-button active':'module-button'} onClick={()=>setSelected(active?selected.filter(item=>item!==id):[...selected,id])}>{active?<><Check/>Selected</>:<><Plus/>Activate Module</>}</button></div><div className="market-module-actions"><Link className="button" href={`/register?module=${id}`}>Start Free Trial</Link><Link className="button button-outline" href={`/modules/${id}`}>View Module</Link></div></article>})}</section><section className="shell marketplace-total"><div><span>{selected.length} modules selected · plus £19 core platform</span><b>Estimated monthly total: £{19+modules.filter(module=>selected.includes(module.id)).reduce((sum,module)=>sum+module.price,0)}/month</b></div><Link className="button" href={selected.length?`/checkout?modules=${selected.join(',')}`:'/register'}>{selected.length?'Activate Selected':'Start Free Trial'} <ArrowRight/></Link></section></div>
}
