import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'

const plans = [
  { name: 'Core Platform', price: '19', text: 'Your secure ERP foundation. Add only the modules you need.', users: '10 users', features: ['Secure workspace', 'Core analytics', 'Role-based access', 'Module marketplace'] },
  { name: 'Growth Example', price: '112', text: 'A connected CRM, people and payroll starting point.', users: '10 users', popular: true, features: ['Core platform', 'CRM module', 'HR Management', 'Payroll', 'Workflow automation'] },
  { name: 'Scale', price: 'Custom', text: 'For multi-team or multi-location operations needing control.', users: 'Flexible users', features: ['Your chosen modules', 'Multi-entity controls', 'Custom roles', 'Dedicated success manager', 'Advanced audit logs'] },
]

export const metadata = { title: 'Pricing' }
export default function PricingPage() { return <div className="page-wrap"><section className="page-hero centered"><div className="shell"><span className="kicker">Simple, scalable pricing</span><h1>Pay for the ERP<br />you actually use.</h1><p>Start with the £19 core platform, then activate only the modules your organisation needs.</p><div className="hero-actions pricing-actions"><Link className="button" href="/#cost-builder">Calculate My Cost <ArrowRight/></Link><Link className="button button-outline" href="/#demos">See Live Demo</Link></div></div></section><section className="shell plan-grid">{plans.map(plan=><article className={plan.popular?'plan popular-plan':'plan'} key={plan.name}>{plan.popular&&<span className="plan-label">POPULAR CONFIGURATION</span>}<h2>{plan.name}</h2><p>{plan.text}</p><div className="plan-price">{plan.price!=='Custom'&&<sup>£</sup>}<strong>{plan.price}</strong>{plan.price!=='Custom'&&<span>/month</span>}</div><b>{plan.users} included</b><Link className={plan.popular?'button':'button button-outline'} href={plan.name==='Scale'?'/#contact':'/register'}>{plan.name==='Scale'?'Talk to sales':'Start Free Trial'} <ArrowRight /></Link><ul>{plan.features.map(feature=><li key={feature}><Check />{feature}</li>)}</ul></article>)}</section><section className="shell usage-callout"><div><span className="kicker">Pay as you go</span><h2>Add modules when they create value.</h2><p>Business modules start from £19 per month. No bundled shelfware, lengthy contract, or disruptive reimplementation.</p></div><Link className="button" href="/#cost-builder">Build My ERP <ArrowRight /></Link></section></div> }
